-- Actualización de posiciones titulares CAR fecha 6
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 147;  -- Roman Osella (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 162;  -- Yago Mosquera (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 177;  -- Lisandro Galliano (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 195;  -- Franco Gasco (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 213;  -- Nicolas Pettigrew (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 212;  -- Mateo Masuero (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'HOOKER' WHERE id = 148;  -- Franco Cammaratta (FORWARD -> HOOKER)
UPDATE "Jugador" SET posicion = 'HOOKER' WHERE id = 163;  -- Ignacio Marino (FORWARD -> HOOKER)
UPDATE "Jugador" SET posicion = 'HOOKER' WHERE id = 178;  -- Santiago Rodriguez Bargiela (FORWARD -> HOOKER)
UPDATE "Jugador" SET posicion = 'HOOKER' WHERE id = 194;  -- Mateo Lepiscopo (FORWARD -> HOOKER)
UPDATE "Jugador" SET posicion = 'HOOKER' WHERE id = 261;  -- Marcos Stanic (FORWARD -> HOOKER)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 253;  -- Federico Alvarez (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 164;  -- Jesuan Mosquera (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 196;  -- Juan Ignacio Ghizzoli (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 257;  -- Tomas Bollini (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'PILAR' WHERE id = 230;  -- Marcos Bogo (FORWARD -> PILAR)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 254;  -- Tomas Alonso (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 150;  -- Diego Lorenzo (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 165;  -- Ignacio Rodriguez Ricci (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 199;  -- Mirko sack (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 237;  -- Santiago Lamas (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 232;  -- Luciano Polenta (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 151;  -- Gianluca Gianoli (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 166;  -- Gonzalo Guillani (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 215;  -- Dibacco (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 198;  -- Juan Ignacio Speroni (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'SEGUNDA_LINEA' WHERE id = 233;  -- Franco Cossa (FORWARD -> SEGUNDA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 152;  -- Tomas Aguirre (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 183;  -- Gonzalo Laiño (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 168;  -- Rodrigo Berdomas (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 184;  -- Juan Ignacio Rodriguez (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 252;  -- Agustin Pallares (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 214;  -- Gaston Sonneville (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 167;  -- Lucca Santero (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 201;  -- Ivan Magister (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 182;  -- Patricio Vidal (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 236;  -- Bruno Massimi (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 234;  -- Joaquin Polenta (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 251;  -- Ignacio Ramos (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 154;  -- Mateo Gonzalez ( C) (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 200;  -- Tomas Tarula (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 169;  -- Agustin Dalto (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 260;  -- Ignacio Lisica (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'TERCERA_LINEA' WHERE id = 218;  -- Gonzalo Siragusa (FORWARD -> TERCERA_LINEA)
UPDATE "Jugador" SET posicion = 'MEDIO_SCRUM' WHERE id = 155;  -- Bruno Zurniewicz (BACK -> MEDIO_SCRUM)
UPDATE "Jugador" SET posicion = 'MEDIO_SCRUM' WHERE id = 170;  -- Franco Sgroi (BACK -> MEDIO_SCRUM)
UPDATE "Jugador" SET posicion = 'MEDIO_SCRUM' WHERE id = 185;  -- Juan Ignacio Maschietto (BACK -> MEDIO_SCRUM)
UPDATE "Jugador" SET posicion = 'MEDIO_SCRUM' WHERE id = 202;  -- Axel rud (BACK -> MEDIO_SCRUM)
UPDATE "Jugador" SET posicion = 'MEDIO_SCRUM' WHERE id = 238;  -- Nicolas Nadal (BACK -> MEDIO_SCRUM)
UPDATE "Jugador" SET posicion = 'MEDIO_SCRUM' WHERE id = 219;  -- Serafin Perez (BACK -> MEDIO_SCRUM)
UPDATE "Jugador" SET posicion = 'APERTURA' WHERE id = 171;  -- Santiago Speroni (BACK -> APERTURA)
UPDATE "Jugador" SET posicion = 'APERTURA' WHERE id = 186;  -- Federico Ban (BACK -> APERTURA)
UPDATE "Jugador" SET posicion = 'APERTURA' WHERE id = 255;  -- Agustin Arone (BACK -> APERTURA)
UPDATE "Jugador" SET posicion = 'APERTURA' WHERE id = 203;  -- Pedro Weiz (BACK -> APERTURA)
UPDATE "Jugador" SET posicion = 'APERTURA' WHERE id = 220;  -- Jose Weiz (BACK -> APERTURA)
UPDATE "Jugador" SET posicion = 'APERTURA' WHERE id = 239;  -- Di Pascuale Juan Manuel (BACK -> APERTURA)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 157;  -- Juan Cruz Procopick (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 172;  -- Juan Bugge (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 193;  -- Santino Oyero (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 204;  -- Ignacio Fernandez (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 229;  -- Santino Curatiola (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 244;  -- Santiago Muzzupapa (BACK -> WING)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 158;  -- Ian Verva (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 188;  -- Marco Gianoli (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 205;  -- Juan Cruz Ratti (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 222;  -- Hipolito Boga (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 241;  -- Bautista Corrales (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 248;  -- Thiago Miñio (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 174;  -- Tomas Lemes (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 192;  -- Lautaro Lopez Badia (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 189;  -- Olvier Ortiz (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 223;  -- Fausto Pelossi (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 247;  -- Nicolas Villalba (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'CENTRO' WHERE id = 249;  -- Velentin campos Cafiero (BACK -> CENTRO)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 160;  -- Thiago Panes (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 187;  -- Bernardo Novak (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 190;  -- Matias Vilarriño (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 256;  -- Ramiro Berdeski (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 224;  -- Ivan Panzitta Forastiero (BACK -> WING)
UPDATE "Jugador" SET posicion = 'WING' WHERE id = 258;  -- Julian Chan (FORWARD -> WING)
UPDATE "Jugador" SET posicion = 'FULLBACK' WHERE id = 176;  -- Juan Pollet (BACK -> FULLBACK)
UPDATE "Jugador" SET posicion = 'FULLBACK' WHERE id = 161;  -- Juan Almandoz (BACK -> FULLBACK)
UPDATE "Jugador" SET posicion = 'FULLBACK' WHERE id = 208;  -- Jeronimo Travin (BACK -> FULLBACK)
UPDATE "Jugador" SET posicion = 'FULLBACK' WHERE id = 209;  -- Ezequiel Yanibelli (BACK -> FULLBACK)
UPDATE "Jugador" SET posicion = 'FULLBACK' WHERE id = 225;  -- Matias Minski (BACK -> FULLBACK)